name: build-rust-std

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build python3 git curl xz-utils

      - name: Download LLVM
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.2/LLVM-22.1.2-Linux-X64.tar.xz
          tar -xf LLVM-22.1.2-Linux-X64.tar.xz
          mv LLVM-22.1.2-Linux-X64 llvm

      - name: Clone Rust
        run: |
          git clone https://github.com/rust-lang/rust.git
          cd rust
          git checkout 1.94.1

      - name: Configure
        run: |
          cd rust
          cat << 'EOF' > config.toml
          [build]
          target = ["aarch64-linux-android", "armv7-linux-androideabi"]

          [rust]
          codegen-units = 1

          [target.aarch64-linux-android]
          cc = "../llvm/bin/clang"
          cxx = "../llvm/bin/clang++"

          [target.armv7-linux-androideabi]
          cc = "../llvm/bin/clang"
          cxx = "../llvm/bin/clang++"
          EOF

      - name: Build std only
        run: |
          cd rust
          ./x.py build library/std --target aarch64-linux-android,armv7-linux-androideabi

      - name: Package artifacts
        run: |
          cd rust
          mkdir -p /tmp/rust-std

          cp -r build/*/stage2/lib/rustlib/aarch64-linux-android /tmp/rust-std/
          cp -r build/*/stage2/lib/rustlib/armv7-linux-androideabi /tmp/rust-std/

          tar -czf rust-std-android.tar.gz -C /tmp rust-std

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-std-android
          path: rust-std-android.tar.gz
